### ISSUE TITLE
解码时数组的顺序混乱

### ISSUE THREAD

**Issue by gaohuacq** [leeqvip/gophp#11]
unserialize.go文件中对数组解码时,原来是利用range遍历map,但因为map是无序的,所以需要先获取键值,按照键值排序然后再插入切片中,同时还需导入sort包
原代码:
for _, row := range val {
	slice = append(slice, row)
}
更新后:
for k,_ := range val {
	keys = append(keys, k)
}
sort.Strings(keys)
for _,k := range keys {
	slice = append(slice, val[k])
}

**Comment by leeqvip** [comment]
@gaohuacq Can you make a PR ?

**Comment by gaohuacq** [comment]
Yes,but I need access to make it
