### ISSUE TITLE
切片反序列化顺序有问题

### ISSUE THREAD

**Issue by ChZhg123** [leeqvip/gophp#15]

**Comment by ChZhg123** [comment]
示例：`a:7:{i:0;a:5:{s:5:"child";a:0:{}s:2:"id";i:1;s:4:"name";s:6:"首页";s:3:"pid";i:0;s:3:"url";s:1:"/";}i:1;a:5:{s:5:"child";a:0:{}s:2:"id";i:2;s:4:"name";s:12:"文学摘抄";s:3:"pid";i:0;s:3:"url";s:17:"/list?type=1&id=2";}i:2;a:5:{s:5:"child";a:0:{}s:2:"id";i:3;s:4:"name";s:12:"技术杂谈";s:3:"pid";i:0;s:3:"url";s:17:"/list?type=1&id=1";}i:3;a:5:{s:5:"child";a:0:{}s:2:"id";i:4;s:4:"name";s:12:"收藏语录";s:3:"pid";i:0;s:3:"url";s:10:"/quotation";}i:4;a:5:{s:5:"child";a:0:{}s:2:"id";i:5;s:4:"name";s:12:"个人日记";s:3:"pid";i:0;s:3:"url";s:6:"/diary";}i:5;a:5:{s:5:"child";a:0:{}s:2:"id";i:6;s:4:"name";s:12:"关于博主";s:3:"pid";i:0;s:3:"url";s:6:"/about";}i:6;a:5:{s:5:"child";a:0:{}s:2:"id";i:7;s:4:"name";s:9:"留言版";s:3:"pid";i:0;s:3:"url";s:6:"/leave";}}`

每次反序列化后切片的顺序都是混乱随机的

**Comment by ChZhg123** [comment]
解决方法：在unserialize.go文件中第205行改为
`var slice []interface{}`
`keys := make([]string, 0)`
`for k := range val {`
`     keys = append(keys, k)`
`}`
`for _, k := range keys {`
`     slice = append(slice, val[k])`
`}`

**Comment by leeqvip** [comment]
It has been fixed #14
