### ISSUE TITLE
序列化方法问题

### ISSUE THREAD

**Issue by 18737836530** [leeqvip/gophp#5]
github.com/techoner/gophp/serialize/serialize.go中22行缺少reflect.Uint8类型,导致一些序列化报错

**Comment by techoner** [comment]
你可以提个PR吗

**Comment by ChZhg123** [comment]
确实少了reflect.Uint8类型 @leeqvip 有空能加上吗

**Comment by leeqvip** [comment]
@ChZhg123  麻烦提个PR呗？

**Comment by yinloo-ola** [comment]
handled in https://github.com/leeqvip/gophp/pull/19
